import test from 'node:test';import assert from 'node:assert/strict';
import {environment,seed,put} from './harness.mjs';
import {createWorker} from '../../worker/src/index.ts';
import {digest,opaque,epoch} from '../../worker/src/cloudflare-auth.ts';
import {hashPassword,verifyPassword} from '../../worker/src/passwords.ts';
import {Repository} from '../../worker/src/repository.ts';
import {authenticateSession} from '../../worker/src/cloudflare-auth.ts';
const worker=createWorker(),password='Synthetic-password-123!';

test('duplicate registration preserves the existing account and reserved bootstrap email cannot be claimed',async()=>{
 const env=environment(),a=await account(env);const duplicate=await req(env,'/auth/register',{json:{email:'ONE@example.test',password,name:'Replacement',sessionMode:'bearer'}});assert.equal(duplicate.status,409);assert.equal(duplicate.data.error.code,'account-exists');assert.equal((await req(env,'/auth/me',{headers:a.headers})).data.user.displayName,'Synthetic person');
 await env.DB.prepare('INSERT INTO cf_bootstrap(id,email,token_hash,expires_at) VALUES(1,?,?,?)').bind('reserved@example.test',await digest(opaque()),epoch()+300).run();assert.equal((await req(env,'/auth/register',{json:{email:'reserved@example.test',password,name:'Attacker',sessionMode:'bearer'}})).status,409);
});
test('revocation during an in-flight write rolls back the entire transaction',async()=>{
 const env=environment(),a=await account(env,'race@example.test','bearer'),identity=await authenticateSession(new Request('https://sewak.test/auth/me',{headers:a.headers}),env),repo=new Repository(env),actor=await repo.actor(identity);
 await env.DB.prepare('DELETE FROM cf_sessions WHERE id=?').bind(a.session).run();await assert.rejects(repo.commit([{path:'users/'+a.uid,data:{...actor.profile,name:'Forbidden write'}}]),error=>error.code==='aborted');assert.equal((await new Repository(env).data('users/'+a.uid)).name,'Synthetic person');
});
test('recovery is admin-only, one-time, invalidates old sessions and rejects expired invitations',async()=>{
 const env=environment(),owner=await account(env,'owner@example.test','bearer'),customer=await account(env,'recover@example.test','bearer');await env.DB.prepare("UPDATE users SET role='superadmin' WHERE id=?").bind(owner.uid).run();
 const path='/api/actions/createAccountRecoveryInvitation';assert.equal((await req(env,path,{headers:customer.headers,json:{targetUid:owner.uid}})).status,403);
 const invitation=await req(env,path,{headers:owner.headers,json:{targetUid:customer.uid}});assert.equal(invitation.status,200);const input={token:invitation.data.invitation.activationToken,password:'Recovered-password-2026!',sessionMode:'bearer'};
 assert.equal((await req(env,'/auth/activate',{json:input})).status,200);assert.equal((await req(env,'/auth/me',{headers:customer.headers})).status,401);assert.equal((await req(env,'/auth/activate',{json:input})).status,400);await login(env,'recover@example.test',input.password);
 const expired=await req(env,path,{headers:owner.headers,json:{targetUid:customer.uid}});await env.DB.prepare('UPDATE cf_invitations SET expires_at=0 WHERE used_at IS NULL').run();assert.equal((await req(env,'/auth/activate',{json:{...input,token:expired.data.invitation.activationToken}})).status,400);
});
async function req(env,path,{json,headers={},method=json?'POST':'GET'}={}){const response=await worker.fetch(new Request('https://sewak.test'+path,{method,headers:{...(json?{'Content-Type':'application/json'}:{}),...headers},...(json?{body:JSON.stringify(json)}:{})}),env);return {status:response.status,headers:response.headers,data:await response.json()};}
async function account(env,email='one@example.test',transport='cookie'){const r=await req(env,'/api/auth/register',{json:{email,password,name:'Synthetic person',sessionMode:transport},headers:transport==='cookie'?{Origin:'https://sewak.test'}:{}});assert.equal(r.status,200,JSON.stringify(r.data));return {uid:r.data.user.uid,csrf:r.data.csrfToken,session:r.data.session.id,token:r.data.token,headers:transport==='cookie'?{Origin:'https://sewak.test',Cookie:r.headers.get('Set-Cookie').split(';')[0],'X-CSRF-Token':r.data.csrfToken}:{Authorization:'Bearer '+r.data.token},response:r};}
async function login(env,email='one@example.test',pw=password){const r=await req(env,'/auth/login',{json:{email,password:pw,sessionMode:'bearer'}});assert.equal(r.status,200,JSON.stringify(r.data));return {headers:{Authorization:'Bearer '+r.data.token},session:r.data.session.id,token:r.data.token};}

test('versioned scrypt hashes use unique salts and reject incorrect passwords/parameters',()=>{const a=hashPassword(password),b=hashPassword(password);assert.notEqual(a,b);assert.ok(verifyPassword(password,a));assert.equal(verifyPassword('wrong',a),false);assert.equal(verifyPassword(password,a.replace('32768','1024')),false);assert.equal(verifyPassword(password,'plaintext'),false);});
test('registration creates a new identity without adopting dummy UID, fields or privileges',async()=>{const env=environment();await seed(env);const a=await account(env,'customer@example.test');assert.notEqual(a.uid,'customer');assert.equal(a.response.data.user.role,'user');assert.equal((await env.DB.prepare('SELECT role FROM users WHERE id=?').bind('customer').first()).role,'user');assert.equal((await req(env,'/api/auth/register',{json:{email:'escalate@example.test',password,name:'Attacker',role:'superadmin'},headers:{Origin:'https://sewak.test'}})).status,400);assert.equal((await req(env,'/api/auth/register',{json:{email:'short@example.test',password:'short',name:'Test'},headers:{Origin:'https://sewak.test'}})).status,400);assert.equal((await req(env,'/api/records/users/customer',{headers:a.headers})).status,403);});
test('web cookie is Secure HttpOnly host-only; token is hashed in D1 and not returned to JavaScript',async()=>{const env=environment(),a=await account(env);const cookie=a.response.headers.get('set-cookie');for(const part of ['__Host-sewak_session=','HttpOnly','Secure','SameSite=Lax','Path=/'])assert.ok(cookie.includes(part));assert.ok(!cookie.includes('Domain='));assert.equal(a.token,undefined);const row=await env.DB.prepare('SELECT * FROM cf_sessions').first();assert.match(row.token_hash,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(row).includes(cookie.split('=')[1].split(';')[0]));assert.equal((await req(env,'/auth/me',{headers:a.headers})).data.user.uid,a.uid);});
test('cookie CSRF, foreign origins, cookie/bearer mixing and browser bearer issuance fail closed',async()=>{const env=environment(),a=await account(env);const change={currentPassword:password,newPassword:'Changed-password-456!'};for(const headers of [{Cookie:a.headers.Cookie},{...a.headers,'X-CSRF-Token':'forged'},{...a.headers,Origin:'https://evil.test'}])assert.equal((await req(env,'/auth/change-password',{json:change,headers})).status,403);assert.equal((await req(env,'/auth/me',{headers:{...a.headers,Authorization:'Bearer '+opaque()}})).status,400);assert.equal((await req(env,'/auth/login',{json:{email:'one@example.test',password,sessionMode:'bearer'},headers:{Origin:'https://sewak.test'}})).status,403);assert.equal((await req(env,'/auth/register',{json:{email:'other@example.test',password,name:'Test'}})).status,403);});
test('opaque mobile sessions, token tampering, transport binding, anonymous and IDOR boundaries',async()=>{const env=environment(),a=await account(env,'one@example.test','bearer'),b=await account(env,'two@example.test','bearer');assert.match(a.token,/^swk_[A-Za-z0-9_-]{43}$/);assert.equal((await req(env,'/api/records/users/'+a.uid,{headers:a.headers})).status,200);assert.equal((await req(env,'/api/records/users/'+b.uid,{headers:a.headers})).status,403);assert.equal((await req(env,'/api/records/users/'+a.uid)).status,401);assert.equal((await req(env,'/api/media/profile_'+a.uid)).status,403);assert.equal((await req(env,'/api/media/profile_'+a.uid,{headers:a.headers})).status,404);for(const token of ['invalid.token.jwt',opaque(),a.token.slice(0,-2)+'aa'])assert.equal((await req(env,'/auth/me',{headers:{Authorization:'Bearer '+token}})).status,401);assert.equal((await req(env,'/auth/me',{headers:{Cookie:'__Host-sewak_session='+a.token}})).status,401);});
test('session audience, absolute expiry, idle expiry and credential version are enforced',async()=>{for(const condition of ['audience','expires_at','last_seen_at','credential_version']){const env=environment(),a=await account(env);await env.DB.prepare(`UPDATE cf_sessions SET ${condition}=?`).bind(condition==='audience'?'another-worker':condition==='credential_version'?100:0).run();assert.equal((await req(env,'/auth/me',{headers:a.headers})).status,401,condition);}});
test('password change verifies current password, invalidates every session, and old password cannot sign in',async()=>{const env=environment(),a=await account(env),b=await login(env);const failed=await req(env,'/auth/change-password',{headers:a.headers,json:{currentPassword:'wrong',newPassword:'Changed-password-456!'}});assert.equal(failed.status,401);assert.equal(failed.headers.get('set-cookie'),null);assert.equal((await req(env,'/auth/change-password',{headers:a.headers,json:{currentPassword:password,newPassword:'Changed-password-456!'}})).status,200);for(const headers of [a.headers,b.headers])assert.equal((await req(env,'/auth/me',{headers})).status,401);assert.equal((await req(env,'/auth/login',{json:{email:'one@example.test',password,sessionMode:'bearer'}})).status,401);await login(env,'one@example.test','Changed-password-456!');});
test('logout and session revocation are server-side and cannot revoke another account',async()=>{const env=environment(),a=await account(env),b=await login(env),other=await account(env,'other@example.test','bearer');assert.equal((await req(env,'/auth/revoke-sessions',{headers:a.headers,json:{sessionId:other.session}})).status,200);assert.equal((await req(env,'/auth/me',{headers:other.headers})).status,200);await req(env,'/auth/revoke-sessions',{headers:a.headers,json:{sessionId:b.session}});assert.equal((await req(env,'/auth/me',{headers:b.headers})).status,401);await req(env,'/auth/logout',{headers:a.headers,json:{}});assert.equal((await req(env,'/auth/me',{headers:a.headers})).status,401);});
test('role authorization reads D1 per request; account suspension revokes access immediately',async()=>{const env=environment();await seed(env);const a=await account(env,'admin-real@example.test','bearer');assert.equal((await req(env,'/api/records/users/customer',{headers:a.headers})).status,403);const c=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(a.uid).first();await env.DB.prepare("UPDATE users SET role='superadmin' WHERE id=?").bind(a.uid).run();assert.equal((await req(env,'/api/records/users/customer',{headers:a.headers})).status,200);await env.DB.prepare("UPDATE users SET role='user' WHERE id=?").bind(a.uid).run();assert.equal((await req(env,'/api/records/users/customer',{headers:a.headers})).status,403);assert.ok(c);await env.DB.prepare('UPDATE cf_credentials SET disabled=1 WHERE user_id=?').bind(a.uid).run();assert.equal((await req(env,'/auth/me',{headers:a.headers})).status,401);});
test('rate limits persist in D1, count failed requests and do not trust client session identifiers',async()=>{const env=environment();for(let i=0;i<10;i++)assert.equal((await req(env,'/auth/login',{json:{email:'missing@example.test',password,sessionMode:'bearer'}})).status,401);const blocked=await req(env,'/auth/login',{json:{email:'MISSING@example.test',password,sessionMode:'bearer'}});assert.equal(blocked.status,429);assert.ok(blocked.headers.get('Retry-After'));});
test('read-only maintenance permits account sign-in/registration but blocks application commits and admin actions',async()=>{const env=environment();env.APP_WRITES_ENABLED='false';const a=await account(env,'readonly@example.test','bearer');assert.equal((await req(env,'/auth/me',{headers:a.headers})).status,200);for(const path of ['/api/commit','/api/actions/provisionSuperAdminAccount'])assert.equal((await req(env,path,{headers:a.headers,json:{}})).status,503);assert.equal((await req(env,'/api/health')).data.auth,'cloudflare-d1');});
test('bootstrap is email-bound, expiring, atomic and single-use; legacy admin data cannot claim it',async()=>{const env=environment();await seed(env);const token=opaque();await env.DB.prepare('INSERT INTO cf_bootstrap(id,email,token_hash,expires_at) VALUES(1,?,?,?)').bind('owner@example.test',await digest(token),epoch()+300).run();const body={email:'owner@example.test',password,name:'Owner',bootstrapToken:token,sessionMode:'bearer'};assert.equal((await req(env,'/auth/bootstrap',{json:{...body,email:'attacker@example.test'}})).status,403);const a=await req(env,'/auth/bootstrap',{json:body});assert.equal(a.status,200,JSON.stringify(a.data));assert.equal(a.data.user.role,'superadmin');assert.notEqual(a.data.user.uid,'admin');assert.equal((await req(env,'/auth/bootstrap',{json:body})).status,403);assert.ok((await env.DB.prepare('SELECT used_at FROM cf_bootstrap').first()).used_at);});
test('organization/caregiver/admin invitations are atomic, hashed and single-use; all four roles retain boundaries',async()=>{const env=environment();const owner=await account(env,'owner@example.test','bearer');await env.DB.prepare("UPDATE users SET role='superadmin' WHERE id=?").bind(owner.uid).run();const org=await req(env,'/api/actions/provisionOrganizationAccount',{headers:owner.headers,json:{email:'organization@example.test',displayName:'Owner Org',organizationName:'Test Org'}});assert.equal(org.status,200,JSON.stringify(org.data));const token=org.data.invitation.activationToken;assert.ok(!(await env.DB.prepare('SELECT token_hash FROM cf_invitations').first()).token_hash.includes(token));const orgLogin=await req(env,'/auth/activate',{json:{token,password,sessionMode:'bearer'}});assert.equal(orgLogin.status,200,JSON.stringify(orgLogin.data));assert.equal(orgLogin.data.user.role,'orgadmin');assert.equal((await req(env,'/auth/activate',{json:{token,password,sessionMode:'bearer'}})).status,400);assert.equal((await req(env,'/api/records/users/'+owner.uid,{headers:{Authorization:'Bearer '+orgLogin.data.token}})).status,403);const approve=await req(env,'/api/actions/approveOrganizationAccount',{headers:owner.headers,json:{organizationId:org.data.uid}});assert.equal(approve.status,200,JSON.stringify(approve.data));const staff=await req(env,'/api/actions/provisionCaregiverAccount',{headers:{Authorization:'Bearer '+orgLogin.data.token},json:{email:'staff@example.test',displayName:'Staff Person',phone:'9800000000',location:'Hetauda',category:'caregiver',workType:'parttime',shifts:['morning'],servicesOffered:[],hourlyRate:500,experience:2}});assert.equal(staff.status,200,JSON.stringify(staff.data));const staffLogin=await req(env,'/auth/activate',{json:{token:staff.data.invitation.activationToken,password,sessionMode:'bearer'}});assert.equal(staffLogin.status,200);assert.equal(staffLogin.data.user.role,'caregiver');assert.equal((await req(env,'/api/records/users/'+owner.uid,{headers:{Authorization:'Bearer '+staffLogin.data.token}})).status,403);assert.equal((await req(env,'/api/actions/applyAccountSafetyAction',{headers:owner.headers,json:{targetType:'organization',targetId:org.data.uid,reason:'Synthetic restriction'}})).status,200);assert.equal((await req(env,'/auth/me',{headers:{Authorization:'Bearer '+staffLogin.data.token}})).status,401);});
